so-setup-network.sh

Check for socore in /etc/sudoers prior to append

---

salt/filebeat/init.sls
salt/firewall/init.sls
salt/top.sls
salt/wazuh/files/agent/ossec.conf
salt/wazuh/files/agent/wazuh-register-agent
salt/wazuh/init.sls
so-setup-network.sh

- Various updates for Wazuh
- Add auth pillar for eval mode to prevent setup errors

Wazuh updates

---

salt/filebeat/etc/filebeat.yml
salt/filebeat/init.sls
salt/logstash/files/dynamic/0006_input_beats.conf

- Wazuh archive logs added to Filebeat config
- Alter LS input for Beats to prep Wazuh logs

Wazuh archive logs

---

salt/filebeat/etc/filebeat.yml
salt/filebeat/init.sls
salt/firewall/init.sls
salt/top.sls
salt/wazuh/files/agent/ossec.conf
salt/wazuh/files/agent/wazuh-register-agent

- Fix firewall logic for Wazuh installs on sensors
- Fix local agent conf logic for Wazuh installs on sensors
- Fix agent conf for storage nodes
- Adjust Filebeat config for sensor vs Wazuh only
- Add Wazuh to other roles in top.sls

More Wazuh updates

---

salt/firewall/init.sls
so-setup-network.sh

- Get disk size for Curator when /nsm not present
- Fix firewall sensor ip
- Change `SENSOR` to `sensor` for configure_minion in setup

Various updates

---

salt/fleet/so-fleet-setup.sh

docker is looking for `launcher.crt`

Fix naming issue

---

salt/fleet/so-fleet-setup.sh

-Added missing packs
-Fixed the packages generated timestamp
-Auto-installs osquery on local system (picks the package based on system type - deb or rpm)

Additional functionality/tweaks

---

so-setup-network.sh

Relates to: https://github.com/TOoSmOotH/securityonion-saltstack/issues/84

ensure setup log is consistent

---

so-setup-network.sh

This should make the bond creation distro agnostic.

Added a function to create the network bond using nmcli

---

so-setup-network.sh

We should bring the bond connections up after creating them

Added logging syntax and fixed bond interface bring up

---

so-setup-network.sh

Ubuntu 16.04 seems to not like how the log piping was on a new line so I moved it to the end of the last lines where this was an issue.

Fix logging issue found in Ubuntu 16.04

---

salt/elastalert/files/rules/so/nids2hive.yaml
salt/elastalert/init.sls

- sync default Elastalert rules
- add example hivealerter rule

sync default Elastalert rules

---

salt/logstash/etc/logstash-template.json

For NIDS SID Drilldown dashboard

Add rule_signature mapping

---

salt/common/nginx/nginx.conf.so-master
salt/playbook/files/nav_layer_playbook.json
salt/playbook/files/navigator_config.json
salt/playbook/init.sls

-Added nginx Playbook & Navigator config for `master` role
-Initial commit for Playbook & Navigator salt states

Playbook and Navigator - initial salt config

---

salt/playbook/files/nav_layer_playbook.json
salt/playbook/init.sls
salt/soctopus/init.sls

Bug fixes and sets SOCtopus to `1.1.1`

Playbook & SOCtopus init edits

---

salt/common/nginx/nginx.conf.so-eval
salt/common/nginx/nginx.conf.so-master
salt/firewall/init.sls
salt/hive/init.sls
salt/hive/thehive/etc/application.conf
salt/hive/thehive/etc/cortex-application.conf
salt/hive/thehive/scripts/cortex_init.sh
so-setup-network.sh

Includes:
-Firewall config
-nginx config
-salt state (uses `hive`)
-Init script & app config

Cortex - initial commit

---

pillar/top.sls

https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/96

update pillar/top.sls to match on id instead of host grain

---

salt/soctopus/files/SOCtopus.conf
salt/soctopus/init.sls

Closes https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/83

Soctopus logging

---

salt/ca/init.sls
salt/common/init.sls
salt/patch/os/schedule.sls
salt/playbook/init.sls
salt/utility/bin/crossthestreams.sh
so-setup-network.sh

https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/105
and
https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/106

Upgrade Salt to 2019.2.2 and fix module.run deprecation warnings

---

so-setup-network.sh

https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/105

add mysql python library and dependencies for py3 salt centos7

---

so-setup-network.sh

https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/105

add py3 python-dateutil for salt

---

salt/common/nginx/nginx.conf.so-eval
salt/common/nginx/nginx.conf.so-master
salt/cyberchef/init.sls
salt/firewall/init.sls
salt/top.sls

Adds Salt config for Cyberchef

Add Cyberchef

---

so-setup-network.sh

https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/105

target install directory for mysql, docker and dateutil libraries for Salt

---

salt/fleet/init.sls

Closes https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/66

Fleet - New Docker env var for path prefix

---

so-setup-network.sh

https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/116

fix repo for distributed salt install

---

salt/hive/thehive/etc/application.conf
salt/hive/thehive/scripts/cortex_init.sh
so-setup-network.sh

Add additional default organization (other than cortex) and user to allow for analyzer runs from TheHive.

Cortex org changes

---

salt/soctopus/files/templates/generic.template

Changes alert name to be more descriptive

Playbook - thehive alert name change

---

so-setup-network.sh

Solves Security-Onion-Solutions/securityonion-saltstack#110 and several other network issues relating to network install.

Network setup fixes
